title: "Fernanda Haiduk"
description: "Portfólio e materiais"
author: "Fernanda Haiduk"

url: "https://fernandahaiduk.github.io"
baseurl: ""   # obrigatório para sites do tipo usuario.github.io

# USE isto (tema remoto) e NÃO use `theme: ...`
remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown
permalink: /:categories/:title/


