title: "Fernanda Haiduk"
description: "Portfólio e materiais"
author: "Fernanda Haiduk"

url: "https://fernandahaiduk.github.io"
baseurl: "" # obrigatório para sites do tipo usuario.github.io

remote_theme: daviddarnes/alembic

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Navegação (cabeçalho)
navigation_header:
  - title: "Inicial"
    url: /
  - title: "Resumo"
    url: /resumo/
  - title: "Projetos"
    url: /projetos/
  - title: "Publicações"
    url: /publicacoes/
  - title: "Contato"
    url: /contato/
  - title: "Ensino"
    url: /ensino/
  - title: "Materiais"
    url: /materiais/
  - title: "Eventos"
    url: /eventos/

# Navegação (rodapé)
navigation_footer:
  - title: "Inicial"
    url: /

# Úteis (opcional)
markdown: kramdown
permalink: /:categories/:title/
