title: "Fernanda Haiduk"
email: "seu-email@exemplo.com"
description: "Especialista Educacional, Desenvolvimento de Conteúdo e Avaliação | Pesquisa em Ensino de Física e Análise de Didáticos | Professora de Física | Análise de Dados Educacionais (Power BI & R) | Desenvolvimento em HTML Simples"
baseurl: "" 
url: "https://fernandahaiduk.github.io"
theme: minima

# Social
github_username: fernandahaiduk
linkedin_username: fernandahaiduk
twitter_username: ""
instagram_username: ""

# Google Analytics
google_analytics: ""

# Build settings
markdown: kramdown

# Incluir pastas adicionais
include:
  - _includes
  - assets/css
